require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/routes.rb'
    - 'config/environments/*.rb'
    - 'app/admin/*rb'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
  Exclude:
    - 'db/migrate/*.rb'

Rails:
  Enabled: true

RSpec:
  Language:
    ExampleGroups:
      Regular:
        - response
    Examples:
      Regular:
        - run_test!

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Enabled: true
  CountAsOne:
    - array
    - hash
    - heredoc

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: true
  Max: 10

RSpec/NestedGroups:
  Enabled: false

RSpec/VariableName:
   EnforcedStyle: snake_case
   AllowedPatterns:
     - ^Authorization$

Style/Documentation:
  Enabled: false

Style/NegatedIf:
  EnforcedStyle: postfix

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
