version: "3"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust"
  redis:
    image: redis
    ports:
      - 6379:6379
  setup:
    environment:
      RAILS_ENV: "test"
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432"
    depends_on:
      - postgres
      - redis
    build: .
    command: >
      sh -c "
        bundle exec rails db:setup
      "
  tests:
    environment:
      RAILS_ENV: "test"
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432"
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
    depends_on:
      - setup
    build: .
    command: sh -c "bundle exec rspec spec"
