version: "3"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "collation_test_user"
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: "trust"
  redis:
    image: redis
    ports:
      - 6379:6379
  setup:
    environment:
      POSTGRES_USER: "collation_test_user"
      POSTGRES_PASSWORD: ""
      RAILS_ENV: "test"
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432"
    depends_on:
      - postgres
      - redis
    build: .
    command: >
      sh -c "
        bundle exec rails db:setup
      "
  tests:
    environment:
      POSTGRES_USER: "collation_test_user"
      POSTGRES_PASSWORD: ""
      RAILS_ENV: "test"
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432"
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: 'true'
      RAILS_MASTER_KEY: "${RAILS_MASTER_KEY}"
    depends_on:
      - setup
    build: .
    command: sh -c "bundle exec rspec spec"
