name: Deployment
on:
  push:
    branches:
      - $default-branch
      - develop

permissions:
  contents: read

jobs:
  dev_deployment:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy to dev dokku
        uses: dokku/github-action@master
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          git_remote_url: ${{ secrets.DEV_DEPLOY_REMOTE_URL }}
          git_push_flags: --force
  stg_deployment:
    runs-on: ubuntu-latest
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy to staging dokku
        uses: dokku/github-action@master
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          git_remote_url: ${{ secrets.STG_DEPLOY_REMOTE_URL }}
          git_push_flags: --force
