name: Deployment
on:
  push:
    branches: [$default-branch, develop]

permissions:
  contents: read
  pull-requests: read

jobs:
  dev_deployment:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: ${{ secrets.DEV_DOKKU_HOST }}
          app-name: ${{ secrets.DEV_DOKKU_APP }}
          git-push-flags: --force
  stg_deployment:
    runs-on: ubuntu-latest
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: ${{ secrets.STG_DOKKU_HOST }}
          app-name: ${{ secrets.STG_DOKKU_APP }}
          git-push-flags: --force
