name: Deployment
on:
  push:
    branches:
      - staging
      - develop

permissions:
  contents: read
  actions: write

jobs:
  dev_deployment:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy to dev dokku
        uses: dokku/github-action@master
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          git_remote_url: ${{ secrets.DEV_DEPLOY_REMOTE_URL }}
          git_push_flags: --force
  stg_deployment:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy to staging dokku
        uses: dokku/github-action@master
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          git_remote_url: ${{ secrets.STG_DEPLOY_REMOTE_URL }}
          git_push_flags: --force
