name: Ruby
on:
  pull_request:
  pull_request_target: [closed]

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker images
        run: docker-compose --env-file=".ci/env" build
      - name: Run setup
        run: RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }} docker-compose --env-file=".ci/env" run setup
      - name: Run test
        run: RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }} docker-compose --env-file=".ci/env" run tests
