name: Ruby
on:
  pull_request:
    types: [opened, synchronize, closed, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker images
        run: docker-compose --env-file=".ci/env" build
      - name: Run setup
        run: docker-compose --env-file=".ci/env" run setup
      - name: Run test
        run: docker-compose --env-file=".ci/env" run tests
