name: Ruby
on:
  push:
    branches: [$default-branch]
  pull_request:
    types: [opened, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker images
        run: docker-compose build
      - name: Run test
        env:
          RAILS_MASTER_KEY: '${{ secrets.RAILS_MASTER_KEY }}'
        run: docker-compose run tests -e RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
